### ISSUE TITLE
React Injection ?

### ISSUE THREAD

**Issue by Devaliel** [RSUD-Dr-Sam-Ratulangi/SistemInformasiPengadaanRsudSamrat#8]
react pe dependencies check ulang masa mo install satu2 dpe dependencies ba nya so depecreted

**Comment by narivay** [comment]
Okk ka tsmo cek

**Comment by Devaliel** [comment]
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
